import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/common/Navbar";
import ThemeProviderWrapper from "@/components/common/ThemeProvider";
import Footer from "@/components/common/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`h-[100vh] w-[100vw] ${inter.className} overflow-x-hidden bg-white dark:bg-[#090D1F]`}
      >
        <ThemeProviderWrapper>
          <div className="h-full w-full flex flex-col">
            <Navbar />
            {children}
            <Footer />
          </div>
        </ThemeProviderWrapper>
      </body>
    </html>
  );
}
